<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE tms_config [
<!ELEMENT tms_config (corridor | camera | commlink | controller | dms)*>
<!ATTLIST tms_config time_stamp CDATA #REQUIRED>
<!ELEMENT corridor (r_node)*>
<!ATTLIST corridor route CDATA #REQUIRED>
<!ATTLIST corridor dir CDATA #REQUIRED>
<!ELEMENT r_node (detector | meter)*>
<!ATTLIST r_node name CDATA #REQUIRED>
<!ATTLIST r_node n_type CDATA 'Station'>
<!ATTLIST r_node pickable CDATA 'f'>
<!ATTLIST r_node above CDATA 'f'>
<!ATTLIST r_node transition CDATA 'None'>
<!ATTLIST r_node station_id CDATA #IMPLIED>
<!ATTLIST r_node label CDATA ''>
<!ATTLIST r_node lon CDATA #REQUIRED>
<!ATTLIST r_node lat CDATA #REQUIRED>
<!ATTLIST r_node lanes CDATA '0'>
<!ATTLIST r_node attach_side CDATA 'right'>
<!ATTLIST r_node shift CDATA '0'>
<!ATTLIST r_node active CDATA 't'>
<!ATTLIST r_node abandoned CDATA 'f'>
<!ATTLIST r_node s_limit CDATA '55'>
<!ATTLIST r_node forks CDATA #IMPLIED>
<!ELEMENT detector EMPTY>
<!ATTLIST detector name CDATA #REQUIRED>
<!ATTLIST detector label CDATA 'FUTURE'>
<!ATTLIST detector abandoned CDATA 'f'>
<!ATTLIST detector category CDATA ''>
<!ATTLIST detector lane CDATA '0'>
<!ATTLIST detector field CDATA '22.0'>
<!ATTLIST detector controller CDATA #IMPLIED>
<!ELEMENT meter EMPTY>
<!ATTLIST meter name CDATA #REQUIRED>
<!ATTLIST meter lon CDATA #IMPLIED>
<!ATTLIST meter lat CDATA #IMPLIED>
<!ATTLIST meter storage CDATA #REQUIRED>
<!ATTLIST meter max_wait CDATA '240'>
<!ELEMENT camera EMPTY>
<!ATTLIST camera name CDATA #REQUIRED>
<!ATTLIST camera description CDATA #REQUIRED>
<!ATTLIST camera lon CDATA #IMPLIED>
<!ATTLIST camera lat CDATA #IMPLIED>
<!ELEMENT commlink EMPTY>
<!ATTLIST commlink name CDATA #REQUIRED>
<!ATTLIST commlink description CDATA #REQUIRED>
<!ATTLIST commlink protocol CDATA #REQUIRED>
<!ELEMENT controller EMPTY>
<!ATTLIST controller name CDATA #REQUIRED>
<!ATTLIST controller active CDATA #REQUIRED>
<!ATTLIST controller drop CDATA #REQUIRED>
<!ATTLIST controller commlink CDATA #IMPLIED>
<!ATTLIST controller lon CDATA #IMPLIED>
<!ATTLIST controller lat CDATA #IMPLIED>
<!ATTLIST controller location CDATA #REQUIRED>
<!ATTLIST controller cabinet CDATA #IMPLIED>
<!ATTLIST controller notes CDATA #IMPLIED>
<!ELEMENT dms EMPTY>
<!ATTLIST dms name CDATA #REQUIRED>
<!ATTLIST dms description CDATA #REQUIRED>
<!ATTLIST dms lon CDATA #IMPLIED>
<!ATTLIST dms lat CDATA #IMPLIED>
<!ATTLIST dms width_pixels CDATA #IMPLIED>
<!ATTLIST dms height_pixels CDATA #IMPLIED>
]>
<tms_config time_stamp='Tue Oct 02 20:00:05 CDT 2018'>
<corridor route='12th St SW' dir='SB'>
  <r_node name='rnd_4291' lon='-92.48221' lat='44.00701' lanes='3' shift='7' s_limit='60'/>
</corridor>
<corridor route='Big Spunk RA' dir='EB'>
  <r_node name='rnd_7199' n_type='Entrance' transition='Common' label='I-94 EB' lon='-94.48746' lat='45.60591' lanes='1' attach_side='left' shift='5'/>
  <r_node name='rnd_6459' lon='-94.48424' lat='45.60418' lanes='1' shift='6'/>
  <r_node name='rnd_7007' lon='-94.48413' lat='45.60406' lanes='1' shift='6'>
    <detector name='8680' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8681' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7152' lon='-94.48405' lat='45.60404' lanes='1' shift='6'>
    <detector name='8682' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8683' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7190' lon='-94.48397' lat='45.60401' lanes='1' shift='6'>
    <detector name='8684' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8685' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7227' lon='-94.48388' lat='45.60399' lanes='1' shift='6'>
    <detector name='8686' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8687' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7232' lon='-94.48378' lat='45.60396' lanes='1' shift='6'>
    <detector name='8688' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8689' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7233' lon='-94.48369' lat='45.60393' lanes='1' shift='6'>
    <detector name='8690' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8691' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7241' lon='-94.48361' lat='45.60389' lanes='1' shift='6'>
    <detector name='8692' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8693' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7266' lon='-94.4834' lat='45.60384' lanes='1' shift='6'>
    <detector name='8694' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8695' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7267' lon='-94.48332' lat='45.60383' lanes='1' shift='6'>
    <detector name='8696' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8697' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7268' lon='-94.48324' lat='45.60379' lanes='1' shift='6'>
    <detector name='8698' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8699' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7269' lon='-94.48316' lat='45.60378' lanes='1' shift='6'>
    <detector name='8700' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8701' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7270' lon='-94.48309' lat='45.60377' lanes='1' shift='6'>
    <detector name='8702' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8703' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7271' lon='-94.48302' lat='45.60374' lanes='1' shift='6'>
    <detector name='8704' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8705' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7272' lon='-94.48296' lat='45.60373' lanes='1' shift='6'>
    <detector name='8706' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8707' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7273' lon='-94.4829' lat='45.60372' lanes='1' shift='6'>
    <detector name='8708' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8709' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7274' lon='-94.48283' lat='45.6037' lanes='1' shift='6' active='f'>
    <detector name='8710' category='PK' lane='1' controller='ctl_1256'/>
    <detector name='8711' category='PK' lane='2' controller='ctl_1256'/>
  </r_node>
  <r_node name='rnd_7278' n_type='Exit' transition='Common' label='I-94 EB' lon='-94.4796' lat='45.60326' lanes='1' attach_side='left' shift='5'/>
</corridor>
<corridor route='C.S.A.H.1' dir='NB'>
  <r_node name='rnd_5838' label='T.H.60' lon='-94.91933' lat='43.93146' lanes='2' shift='6' active='f'>
    <detector name='80016' label='CSAH1/TH60N1' lane='1' controller='ctl_134'/>
    <detector name='80017' label='CSAH1/TH60N1' lane='1' controller='ctl_134'/>
  </r_node>
  <r_node name='rnd_5837' label='T.H.60' lon='-94.91935' lat='43.93187' lanes='2' shift='6' active='f'>
    <detector name='80012' label='CSAH1/TH60N1' lane='1' controller='ctl_134'/>
    <detector name='80014' label='CSAH1/TH60N1' lane='1' controller='ctl_134'/>
  </r_node>
  <r_node name='rnd_5778' label='T.H.23' lon='-95.18623' lat='45.04359' lanes='2' shift='6' active='f'>
    <detector name='80019' label='CSAH1/TH23N1' lane='1' controller='ctl_145'/>
  </r_node>
  <r_node name='rnd_5775' label='T.H.23' lon='-95.18625' lat='45.04297' lanes='2' shift='6' active='f'>
    <detector name='80110' label='CSAH1/TH23N1' lane='1' controller='ctl_145'/>
    <detector name='80111' label='CSAH1/TH23N1' lane='1' controller='ctl_145'/>
  </r_node>
  <r_node name='rnd_5861' label='T.H.7' lon='-94.05299' lat='44.90594' lanes='2' shift='6' active='f'>
    <detector name='80116' label='CSAH1/TH7N1' lane='1' controller='ctl_942'/>
    <detector name='80117' label='CSAH1/TH7N1' lane='1' controller='ctl_942'/>
  </r_node>
  <r_node name='rnd_5862' label='T.H.7' lon='-94.05296' lat='44.9047' lanes='2' shift='6' active='f'>
    <detector name='80118' label='CSAH1/TH7N1' lane='1' controller='ctl_942'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.1' dir='SB'>
  <r_node name='rnd_5866' label='T.H.7' lon='-94.05323' lat='44.90639' lanes='2' shift='6' active='f'>
    <detector name='80114' label='CSAH1/TH7S1' lane='1' controller='ctl_942'/>
    <detector name='80115' label='CSAH1/TH7S1' lane='1' controller='ctl_942'/>
  </r_node>
  <r_node name='rnd_5865' label='T.H.7' lon='-94.05323' lat='44.90704' lanes='2' shift='6' active='f'>
    <detector name='80113' label='CSAH1/TH7S1' lane='1' controller='ctl_942'/>
  </r_node>
  <r_node name='rnd_5782' label='T.H.23' lon='-95.18639' lat='45.04471' lanes='2' shift='6' active='f'>
    <detector name='80112' label='CSAH1/TH23S1' lane='1' controller='ctl_145'/>
  </r_node>
  <r_node name='rnd_5779' label='T.H.23' lon='-95.18638' lat='45.0441' lanes='2' shift='6' active='f'>
    <detector name='80018' label='CSAH1/TH23S1' lane='1' controller='ctl_145'/>
  </r_node>
  <r_node name='rnd_5834' label='T.H.60' lon='-94.91943' lat='43.93227' lanes='2' shift='6' active='f'>
    <detector name='80015' label='CSAH1/TH60S1' lane='1' controller='ctl_134'/>
  </r_node>
  <r_node name='rnd_5833' label='T.H.60' lon='-94.91944' lat='43.93203' lanes='2' shift='6' active='f'>
    <detector name='80011' label='CSAH1/TH60S1' lane='1' controller='ctl_134'/>
    <detector name='80013' label='CSAH1/TH60S1' lane='1' controller='ctl_134'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.16' dir='NB'>
  <r_node name='rnd_5716' label='T.H.23' lon='-96.18457' lat='44.08841' lanes='2' shift='6' active='f'>
    <detector name='80165' label='CSAH16/TH23N1' lane='1' controller='ctl_939'/>
  </r_node>
  <r_node name='rnd_5717' label='T.H.23' lon='-96.18456' lat='44.08872' lanes='2' shift='6' active='f'>
    <detector name='80163' label='CSAH16/TH23N1' lane='1' controller='ctl_939'/>
    <detector name='80164' label='CSAH16/TH23N1' lane='1' controller='ctl_939'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.16' dir='SB'>
  <r_node name='rnd_5728' label='T.H.23' lon='-96.18463' lat='44.08924' lanes='2' shift='6' active='f'>
    <detector name='80161' label='CSAH16/TH23S1' lane='1' controller='ctl_939'/>
  </r_node>
  <r_node name='rnd_5731' label='T.H.23' lon='-96.18462' lat='44.08892' lanes='2' shift='6' active='f'>
    <detector name='80162' label='CSAH16/TH23S1' lane='1' controller='ctl_939'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.18' dir='EB'>
  <r_node name='rnd_5805' label='T.H.75' lon='-96.74742' lat='46.90501' lanes='2' shift='6' active='f'>
    <detector name='40181' label='CSAH18/TH75E1' lane='1' controller='ctl_136'/>
  </r_node>
  <r_node name='rnd_5804' label='T.H.75' lon='-96.74649' lat='46.90503' lanes='2' shift='6' active='f'>
    <detector name='40182' label='CSAH18/TH75E1' lane='1' controller='ctl_136'/>
    <detector name='40183' label='CSAH18/TH75E1' lane='1' controller='ctl_136'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.18' dir='WB'>
  <r_node name='rnd_5809' label='T.H.75' lon='-96.74532' lat='46.90508' lanes='2' shift='6' active='f'>
    <detector name='40187' label='CSAH18/TH75W1' lane='1' controller='ctl_136'/>
  </r_node>
  <r_node name='rnd_5808' label='T.H.75' lon='-96.74603' lat='46.90506' lanes='2' shift='6' active='f'>
    <detector name='40184' label='CSAH18/TH75W1' lane='1' controller='ctl_136'/>
    <detector name='40185' label='CSAH18/TH75W1' lane='1' controller='ctl_136'/>
    <detector name='40186' label='CSAH18/TH75W1' lane='1' controller='ctl_136'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.21' dir='WB'>
  <r_node name='rnd_5647' label='T.H.169' lon='-92.42381' lat='47.63263' lanes='2' shift='6' active='f'>
    <detector name='10211' label='CSAH21/TH169W1' lane='1' controller='ctl_126'/>
  </r_node>
  <r_node name='rnd_5648' label='T.H.169' lon='-92.42545' lat='47.63261' lanes='2' shift='6'>
    <detector name='10212' label='CSAH21/TH169W1' lane='1' controller='ctl_126'/>
    <detector name='10213' label='CSAH21/TH169W1' lane='1' controller='ctl_126'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.35' dir='NB'>
  <r_node name='rnd_5720' label='T.H.210 (MP 59.535)' lon='-95.87432' lat='46.28078' lanes='2' shift='6' active='f'>
    <detector name='40358' label='CSAH35/TH210N1' lane='1' controller='ctl_131'/>
  </r_node>
  <r_node name='rnd_5721' label='T.H.210 (MP 59.535)' lon='-95.87432' lat='46.28116' lanes='2' shift='6' active='f'>
    <detector name='40355' label='CSAH35/TH210N1' lane='1' controller='ctl_131'/>
    <detector name='40356' label='CSAH35/TH210N1' lane='1' controller='ctl_131'/>
    <detector name='40357' label='CSAH35/TH210N1' lane='1' controller='ctl_131'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.35' dir='SB'>
  <r_node name='rnd_5729' label='T.H.210 (MP 59.535)' lon='-95.8744' lat='46.28173' lanes='2' shift='6' active='f'>
    <detector name='40351' label='CSAH35/TH210S1' lane='1' controller='ctl_131'/>
  </r_node>
  <r_node name='rnd_5730' label='T.H.210 (MP 59.535)' lon='-95.87441' lat='46.2813' lanes='2' shift='6' active='f'>
    <detector name='40352' label='CSAH35/TH210S1' lane='1' controller='ctl_131'/>
    <detector name='40353' label='CSAH35/TH210S1' lane='1' controller='ctl_131'/>
    <detector name='40354' label='CSAH35/TH210S1' lane='1' controller='ctl_131'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.4' dir='NB'>
  <r_node name='rnd_5738' label='T.H.200' lon='-95.61554' lat='47.32387' lanes='2' shift='6' active='f'>
    <detector name='40044' label='CSAH4/TH200N1' lane='1' controller='ctl_132'/>
  </r_node>
  <r_node name='rnd_5737' label='T.H.200' lon='-95.61555' lat='47.32456' lanes='2' shift='6' active='f'>
    <detector name='40043' label='CSAH4/TH200N1' lane='1' controller='ctl_132'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.4' dir='SB'>
  <r_node name='rnd_5735' label='T.H.200' lon='-95.61576' lat='47.32586' lanes='2' shift='6' active='f'>
    <detector name='40041' label='CSAH4/TH200S1' lane='1' controller='ctl_132'/>
  </r_node>
  <r_node name='rnd_5734' label='T.H.200' lon='-95.61571' lat='47.32478' lanes='2' shift='6' active='f'>
    <detector name='40042' label='CSAH4/TH200S1' lane='1' controller='ctl_132'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.5' dir='EB'>
  <r_node name='rnd_5703' label='T.H.29' lon='-95.31343' lat='46.01989' lanes='2' shift='6' active='f'>
    <detector name='40051' label='CSAH5/TH29E1' lane='1' controller='ctl_129'/>
  </r_node>
  <r_node name='rnd_5702' label='T.H.29' lon='-95.31291' lat='46.0199' lanes='2' shift='6' active='f'>
    <detector name='40052' label='CSAH5/TH29E1' lane='1' controller='ctl_129'/>
    <detector name='40053' label='CSAH5/TH29E1' lane='1' controller='ctl_129'/>
  </r_node>
  <r_node name='rnd_5796' label='T.H.15' lon='-94.42548' lat='44.36568' lanes='2' shift='6' active='f'>
    <detector name='70051' label='CSAH5/TH15E1' lane='1' controller='ctl_137'/>
  </r_node>
  <r_node name='rnd_5795' label='T.H.15' lon='-94.42397' lat='44.36556' lanes='2' shift='6' active='f'>
    <detector name='70052' label='CSAH5/TH15E1' lane='1' controller='ctl_137'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.5' dir='WB'>
  <r_node name='rnd_5793' label='T.H.15' lon='-94.42132' lat='44.36592' lanes='2' shift='6' active='f'>
    <detector name='70054' label='CSAH5/TH15W1' lane='1' controller='ctl_137'/>
  </r_node>
  <r_node name='rnd_5791' label='T.H.15' lon='-94.42309' lat='44.36574' lanes='2' shift='6' active='f'>
    <detector name='70053' label='CSAH5/TH15W1' lane='1' controller='ctl_137'/>
  </r_node>
  <r_node name='rnd_5794' lon='-94.42341' lat='44.36568' lanes='2' shift='6' active='f'/>
  <r_node name='rnd_5707' label='T.H.29' lon='-95.31173' lat='46.01995' lanes='2' shift='6' active='f'>
    <detector name='40056' label='CSAH5/TH29W1' lane='1' controller='ctl_129'/>
    <detector name='40057' label='CSAH5/TH29W1' lane='1' controller='ctl_129'/>
  </r_node>
  <r_node name='rnd_5706' label='T.H.29' lon='-95.31254' lat='46.01995' lanes='2' shift='6' active='f'>
    <detector name='40054' label='CSAH5/TH29W1' lane='1' controller='ctl_129'/>
    <detector name='40055' label='CSAH5/TH29W1' lane='1' controller='ctl_129'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.7 Blvd' dir='NB'>
  <r_node name='rnd_5688' label='T.H.19' lon='-92.7269' lat='44.50177' lanes='2' shift='6' active='f'>
    <detector name='60075' label='CSAH7/TH19N1' lane='1' controller='ctl_944'/>
  </r_node>
  <r_node name='rnd_5687' label='T.H.19' lon='-92.7269' lat='44.50233' lanes='2' shift='6' active='f'>
    <detector name='60074' label='CSAH7/TH19N1' lane='1' controller='ctl_944'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.7 Blvd' dir='SB'>
  <r_node name='rnd_5692' label='T.H.19' lon='-92.72675' lat='44.50342' lanes='2' shift='6' active='f'>
    <detector name='60071' label='CSAH7/TH19S1' lane='1' controller='ctl_944'/>
  </r_node>
  <r_node name='rnd_5691' label='T.H.19' lon='-92.72697' lat='44.50317' lanes='2' shift='6' active='f'>
    <detector name='60072' label='CSAH7/TH19S1' lane='1' controller='ctl_944'/>
  </r_node>
  <r_node name='rnd_5690' label='T.H.19' lon='-92.72699' lat='44.50258' lanes='2' shift='6' active='f'>
    <detector name='60073' label='CSAH7/TH19S1' lane='1' controller='ctl_944'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.7' dir='NB'>
  <r_node name='rnd_5874' label='T.H.23' lon='-95.81647' lat='44.42787' lanes='2' shift='6' active='f'>
    <detector name='80075' label='CSAH7/TH23N1' lane='1' controller='ctl_144'/>
  </r_node>
  <r_node name='rnd_5873' label='T.H.23' lon='-95.81645' lat='44.42859' lanes='2' shift='6' active='f'>
    <detector name='80072' label='CSAH7/TH23N1' lane='1' controller='ctl_144'/>
    <detector name='80073' label='CSAH7/TH23N1' lane='1' controller='ctl_144'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.7' dir='SB'>
  <r_node name='rnd_5877' label='T.H.23' lon='-95.8166' lat='44.42976' lanes='2' shift='6' active='f'>
    <detector name='80074' label='CSAH7/TH23S1' lane='1' controller='ctl_144'/>
  </r_node>
  <r_node name='rnd_5876' label='T.H.23' lon='-95.81659' lat='44.42909' lanes='2' shift='6' active='f'>
    <detector name='80071' label='CSAH7/TH23S1' lane='1' controller='ctl_144'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.77' dir='NB'>
  <r_node name='rnd_5631' lon='-92.3633' lat='47.78503' lanes='2' shift='6' active='f'/>
  <r_node name='rnd_5634' label='T.H.169' lon='-92.36359' lat='47.78525' lanes='2' shift='6'>
    <detector name='10774' label='CSAH77/TH169N1' lane='1' controller='ctl_122'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.77' dir='SB'>
  <r_node name='rnd_5633' lon='-92.36511' lat='47.78647' lanes='2' shift='6' active='f'/>
  <r_node name='rnd_5632' label='T.H.169' lon='-92.36475' lat='47.78612' lanes='2' shift='6'>
    <detector name='10771' label='CSAH77/TH169S1' lane='1' controller='ctl_122'/>
    <detector name='10775' label='CSAH77/TH169S2' lane='2' controller='ctl_122'/>
  </r_node>
  <r_node name='rnd_5628' label='T.H.169' lon='-92.36376' lat='47.78523' lanes='2' shift='6'>
    <detector name='10772' label='CSAH77/TH169S1' lane='1' controller='ctl_122'/>
    <detector name='10773' label='CSAH77/TH169S2' lane='2' controller='ctl_122'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.9' dir='EB'>
  <r_node name='rnd_5777' label='T.H.56' lon='-92.98055' lat='44.40672' lanes='2' shift='6' active='f'>
    <detector name='60095' label='CSAH9/TH56E1' lane='1' controller='ctl_138'/>
  </r_node>
  <r_node name='rnd_5776' label='T.H.56' lon='-92.97994' lat='44.40678' lanes='2' shift='6' active='f'>
    <detector name='60091' label='CSAH9/TH56E1' lane='1' controller='ctl_138'/>
    <detector name='60094' label='CSAH9/TH56E1' lane='1' controller='ctl_138'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.9' dir='WB'>
  <r_node name='rnd_5773' label='T.H.56' lon='-92.97888' lat='44.40694' lanes='2' shift='6' active='f'>
    <detector name='60096' label='CSAH9/TH56W1' lane='1' controller='ctl_138'/>
  </r_node>
  <r_node name='rnd_5774' label='T.H.56' lon='-92.97964' lat='44.40686' lanes='2' shift='6' active='f'>
    <detector name='60092' label='CSAH9/TH56W1' lane='1' controller='ctl_138'/>
    <detector name='60093' label='CSAH9/TH56W1' lane='1' controller='ctl_138'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.98' dir='NB'>
  <r_node name='rnd_5666' label='T.H.2' lon='-92.36461' lat='46.80267' lanes='2' shift='6' active='f'>
    <detector name='10984' label='CSAH98/TH2N1' lane='1' controller='ctl_124'/>
  </r_node>
  <r_node name='rnd_5665' label='T.H.2' lon='-92.36463' lat='46.80341' lanes='2' shift='6'>
    <detector name='10983' label='CSAH98/TH2N1' lane='1' controller='ctl_124'/>
  </r_node>
</corridor>
<corridor route='C.S.A.H.98' dir='SB'>
  <r_node name='rnd_5669' label='T.H.2' lon='-92.36482' lat='46.8055' lanes='2' shift='6' active='f'>
    <detector name='10981' label='CSAH98/TH2S1' lane='1' controller='ctl_124'/>
  </r_node>
  <r_node name='rnd_5670' label='T.H.2' lon='-92.36481' lat='46.80473' lanes='2' shift='6'>
    <detector name='10982' label='CSAH98/TH2S1' lane='1' controller='ctl_124'/>
  </r_node>
</corridor>
<corridor route='Co Rd 120' dir='EB'>
  <r_node name='rnd_5849' label='T.H.29' lon='-95.3177' lat='45.93314' lanes='2' shift='6' active='f'>
    <detector name='41201' label='CR120/TH29E1' lane='1' controller='ctl_943'/>
    <detector name='41202' label='CR120/TH29E1' lane='1' controller='ctl_943'/>
  </r_node>
  <r_node name='rnd_5850' label='T.H.29' lon='-95.31616' lat='45.93314' lanes='2' shift='6' active='f'>
    <detector name='41203' label='CR120/TH29E1' lane='1' controller='ctl_943'/>
  </r_node>
</corridor>
<corridor route='Co Rd 120' dir='WB'>
  <r_node name='rnd_5854' label='T.H.29' lon='-95.31493' lat='45.9332' lanes='2' shift='6' active='f'>
    <detector name='41206' label='CR120/TH29W1' lane='1' controller='ctl_943'/>
  </r_node>
  <r_node name='rnd_5853' label='T.H.29' lon='-95.31567' lat='45.93321' lanes='2' shift='6' active='f'>
    <detector name='41204' label='CR120/TH29W1' lane='1' controller='ctl_943'/>
    <detector name='41205' label='CR120/TH29W1' lane='1' controller='ctl_943'/>
  </r_node>
</corridor>
<corridor route='Co Rd 15' dir='EB'>
  <r_node name='rnd_5901' label='T.H.7' lon='-95.74561' lat='44.94926' lanes='2' shift='6' active='f'>
    <detector name='80151' label='CR15/TH7E1' lane='1' controller='ctl_940'/>
  </r_node>
  <r_node name='rnd_5900' label='T.H.7' lon='-95.74483' lat='44.94926' lanes='2' shift='6' active='f'>
    <detector name='80152' label='CR15/TH7E1' lane='1' controller='ctl_940'/>
  </r_node>
</corridor>
<corridor route='Co Rd 15' dir='WB'>
  <r_node name='rnd_5897' label='T.H.7' lon='-95.74322' lat='44.94938' lanes='2' shift='6' active='f'>
    <detector name='80155' label='CR15/TH7W1' lane='1' controller='ctl_940'/>
  </r_node>
  <r_node name='rnd_5898' label='T.H.7' lon='-95.74404' lat='44.94938' lanes='2' shift='6' active='f'>
    <detector name='80153' label='CR15/TH7W1' lane='1' controller='ctl_940'/>
    <detector name='80154' label='CR15/TH7W1' lane='1' controller='ctl_940'/>
  </r_node>
</corridor>
<corridor route='Co Rd 27' dir='EB'>
  <r_node name='rnd_5888' label='T.H.15' lon='-94.31769' lat='45.19747' lanes='2' shift='6' active='f'>
    <detector name='80271' label='CR27/TH15E1' lane='1' controller='ctl_941'/>
  </r_node>
  <r_node name='rnd_5887' label='T.H.15' lon='-94.31701' lat='45.19747' lanes='2' shift='6' active='f'>
    <detector name='80272' label='CR27/TH15E1' lane='1' controller='ctl_941'/>
    <detector name='80273' label='CR27/TH15E1' lane='1' controller='ctl_941'/>
  </r_node>
</corridor>
<corridor route='Co Rd 27' dir='WB'>
  <r_node name='rnd_5891' label='T.H.15' lon='-94.31555' lat='45.19746' lanes='2' shift='6' active='f'>
    <detector name='80276' label='CR27/TH15W1' lane='1' controller='ctl_941'/>
  </r_node>
  <r_node name='rnd_5890' label='T.H.15' lon='-94.31638' lat='45.19754' lanes='2' shift='6' active='f'>
    <detector name='80274' label='CR27/TH15W1' lane='1' controller='ctl_941'/>
    <detector name='80275' label='CR27/TH15W1' lane='1' controller='ctl_941'/>
  </r_node>
</corridor>
<corridor route='Co Rd 33' dir='NB'>
  <r_node name='rnd_5855' label='T.H.7' lon='-93.97109' lat='44.9041' lanes='2' shift='6' active='f'>
    <detector name='50336' label='CR33/TH7N1' lane='1' controller='ctl_141'/>
    <detector name='50337' label='CR33/TH7N1' lane='1' controller='ctl_141'/>
  </r_node>
  <r_node name='rnd_5860' label='T.H.7' lon='-93.97105' lat='44.90465' lanes='2' shift='6' active='f'>
    <detector name='50335' label='CR33/TH7N1' lane='1' controller='ctl_141'/>
  </r_node>
</corridor>
<corridor route='Co Rd 33' dir='SB'>
  <r_node name='rnd_5851' label='T.H.7' lon='-93.97128' lat='44.90558' lanes='2' shift='6' active='f'>
    <detector name='50333' label='CR33/TH7S1' lane='1' controller='ctl_141'/>
    <detector name='50334' label='CR33/TH7S1' lane='1' controller='ctl_141'/>
  </r_node>
  <r_node name='rnd_5848' label='T.H.7' lon='-93.97123' lat='44.90497' lanes='2' shift='6' active='f'>
    <detector name='50331' label='CR33/TH7S1' lane='1' controller='ctl_141'/>
    <detector name='50332' label='CR33/TH7S1' lane='1' controller='ctl_141'/>
  </r_node>
</corridor>
<corridor route='Co Rd 75' dir='NB'>
  <r_node name='rnd_5755' label='T.H.10' lon='-95.17632' lat='46.45502' lanes='2' shift='6' active='f'>
    <detector name='47754' label='CR75/TH10N1' lane='1' controller='ctl_140'/>
  </r_node>
  <r_node name='rnd_5754' label='T.H.10' lon='-95.17635' lat='46.45626' lanes='2' shift='6' active='f'>
    <detector name='47753' label='CR75/TH10N1' lane='1' controller='ctl_140'/>
  </r_node>
</corridor>
<corridor route='Co Rd 75' dir='SB'>
  <r_node name='rnd_5758' label='T.H.10' lon='-95.17645' lat='46.45775' lanes='2' shift='6' active='f'>
    <detector name='47751' label='CR75/TH10S1' lane='1' controller='ctl_140'/>
  </r_node>
  <r_node name='rnd_5759' label='T.H.10' lon='-95.17643' lat='46.4567' lanes='2' shift='6' active='f'>
    <detector name='47752' label='CR75/TH10S1' lane='1' controller='ctl_140'/>
  </r_node>
</corridor>
<corridor route='Elm Creek RA' dir='EB'>
  <r_node name='rnd_5988' n_type='Entrance' transition='Common' label='I-94 EB' lon='-93.47608' lat='45.1146' lanes='1' attach_side='left' shift='6' s_limit='45'/>
  <r_node name='rnd_4542' lon='-93.47312' lat='45.11171' lanes='1' shift='7' active='f'/>
  <r_node name='rnd_5990' lon='-93.47306' lat='45.11154' lanes='1' shift='7' s_limit='45'>
    <detector name='8521' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8500' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5991' lon='-93.47298' lat='45.1115' lanes='1' shift='7' s_limit='45'>
    <detector name='8522' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8501' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5992' lon='-93.47292' lat='45.11146' lanes='1' shift='7' s_limit='45'>
    <detector name='8502' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8503' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5993' lon='-93.47287' lat='45.11143' lanes='1' shift='7' s_limit='45'>
    <detector name='8504' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8505' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5994' lon='-93.47282' lat='45.1114' lanes='1' shift='7' s_limit='45'>
    <detector name='8506' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8507' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5995' lon='-93.47277' lat='45.11136' lanes='1' shift='7' s_limit='45'>
    <detector name='8508' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8509' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5996' lon='-93.47272' lat='45.11132' lanes='1' shift='7' s_limit='45'>
    <detector name='8510' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8511' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5997' lon='-93.47266' lat='45.11128' lanes='1' shift='7' s_limit='45'>
    <detector name='8512' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8513' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5998' lon='-93.47261' lat='45.11124' lanes='1' shift='7' s_limit='45'>
    <detector name='8523' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8514' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_5999' lon='-93.47256' lat='45.11121' lanes='1' shift='7' s_limit='45'>
    <detector name='8524' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8515' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_6000' lon='-93.4725' lat='45.11117' lanes='1' shift='7' s_limit='45'>
    <detector name='8525' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8516' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_6001' lon='-93.47244' lat='45.11113' lanes='1' shift='7' s_limit='45'>
    <detector name='8526' category='PK' lane='1' controller='ctl_1129'/>
    <detector name='8517' category='PK' lane='2' controller='ctl_1129'/>
  </r_node>
  <r_node name='rnd_6002' lon='-93.47238' lat='45.11108' lanes='1' shift='7' s_limit='45'>